# Local development override
# Usage: docker compose -f docker-compose.yml -f docker-compose.local.yml up -d --build

services:
  piper-tts:
    ports:
      - "5000:5000"
    labels: []
    networks:
      - default

  tts-ui:
    ports:
      - "8081:80"
    labels: []
    networks:
      - default

networks:
  caddy:
    external: false
